import { NextRequest, NextResponse } from "next/server";
import { createServiceClient } from "@/lib/supabase/server";
import { isAuthFailure, requireConnectorAccess } from "@/lib/api/auth";
import { verifySyncToken } from "@/lib/api/sync-token";
import { parseSyncDateRange } from "@/lib/api/validation";
import {
  SyncConfigError,
  syncConnectorTransactions,
} from "@/lib/connectors/sync";

type SyncBody = {
  connector_id?: string;
  org_id?: string;
  from_date?: string;
  to_date?: string;
  /** HMAC token generated server-side at page load. When present, full
   *  Supabase cookie auth is skipped — the token is verified locally with
   *  zero network calls, cutting ~600 ms of auth overhead per chunk. */
  sync_token?: string;
};

export async function handleConnectorSyncRequest(
  req: NextRequest,
  type: string
): Promise<NextResponse> {
  let body: SyncBody;
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON body" }, { status: 400 });
  }

  const { connector_id: connectorId, org_id: orgId, from_date, to_date, sync_token: syncToken } = body;
  if (!connectorId || !orgId) {
    return NextResponse.json(
      { error: "connector_id and org_id are required" },
      { status: 400 }
    );
  }

  const range = parseSyncDateRange(from_date, to_date);
  if ("error" in range) return range.error;

  // ── Fast path: HMAC token verification (zero network calls) ───────────────
  // When the client sends a sync_token (generated by the server component at
  // page load), we skip the 3-round-trip Supabase auth and verify locally.
  // This eliminates the main latency cause of Vercel 504 timeouts.
  if (syncToken && verifySyncToken(syncToken, connectorId, orgId)) {
    const supabase = await createServiceClient();
    const { data: connector, error: connErr } = await supabase
      .from("connectors")
      .select("*")
      .eq("id", connectorId)
      .eq("org_id", orgId)
      .eq("type", type)
      .single();

    if (connErr || !connector) {
      return NextResponse.json({ error: "Connector not found" }, { status: 404 });
    }

    try {
      const result = await syncConnectorTransactions({
        supabase,
        connector,
        fromDate: range.fromDate,
        toDate: range.toDate,
      });

      return NextResponse.json({
        synced:   result.inserted,
        fetched:  result.fetched,
        skipped:  result.skipped,
        updated:  result.updated,
        from:     range.fromDate.toISOString(),
        to:       range.toDate.toISOString(),
        ...(result.warnings.length > 0 ? { warnings: result.warnings } : {}),
      });
    } catch (err) {
      const status = err instanceof SyncConfigError ? 422 : 500;
      return NextResponse.json(
        { error: err instanceof Error ? err.message : "Failed to sync connector" },
        { status }
      );
    }
  }

  // ── Slow path: full Supabase cookie auth (fallback) ───────────────────────
  const auth = await requireConnectorAccess(connectorId, { orgId, type });
  if (isAuthFailure(auth)) return auth.error;

  const { data: connector, error: connErr } = await auth.supabase
    .from("connectors")
    .select("*")
    .eq("id", auth.connector.id)
    .single();

  if (connErr || !connector) {
    return NextResponse.json({ error: "Connector not found" }, { status: 404 });
  }

  try {
    const result = await syncConnectorTransactions({
      supabase: auth.supabase,
      connector,
      fromDate: range.fromDate,
      toDate: range.toDate,
    });

    return NextResponse.json({
      synced:   result.inserted,
      fetched:  result.fetched,
      skipped:  result.skipped,
      updated:  result.updated,
      from:     range.fromDate.toISOString(),
      to:       range.toDate.toISOString(),
      ...(result.warnings.length > 0 ? { warnings: result.warnings } : {}),
    });
  } catch (err) {
    const status = err instanceof SyncConfigError ? 422 : 500;
    return NextResponse.json(
      { error: err instanceof Error ? err.message : "Failed to sync connector" },
      { status }
    );
  }
}
